============================= test session starts ==============================
platform linux2 -- Python 3.2.2 -- pytest-2.2.3
collecting ... collected 4 items

prime_factor.py ...F

=================================== FAILURES ===================================
________________________________ test_primes_4 _________________________________

    def test_primes_4():
>       assert primes(4) == [2, 2]
E       assert [2] == [2, 2]
E         Right contains more items, first extra item: 2

prime_factor.py:25: AssertionError
====================== 1 failed, 3 passed in 0.03 seconds ======================
