============================= test session starts ==============================
platform linux2 -- Python 3.2.2 -- pytest-2.2.3
collecting ... collected 4 items

prime_factor.py ...F

=================================== FAILURES ===================================
________________________________ test_primes_4 _________________________________

    def test_primes_4():
>       assert primes(4) == [2, 2]
E       assert [2, 4] == [2, 2]
E         At index 1 diff: 4 != 2

prime_factor.py:26: AssertionError
------------------------------- Captured stdout --------------------------------
2
2
3
4
4
====================== 1 failed, 3 passed in 0.03 seconds ======================
